import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { AlertCircle, ChevronDown } from 'lucide-react'

export default function MedicalDisclaimerFull({ defaultOpen = false }) {
  const [open, setOpen] = useState(defaultOpen)

  return (
    <div className="rounded-ios-lg border border-amber-200/70 bg-amber-50 overflow-hidden">
      <button
        onClick={() => setOpen((v) => !v)}
        className="w-full flex items-center gap-3 px-4 py-3.5 text-left"
      >
        <AlertCircle size={18} className="text-amber-600 shrink-0" />
        <span className="flex-1 text-[13px] font-semibold text-amber-800">
          Medical Disclaimer — Read Before Use
        </span>
        <motion.div
          animate={{ rotate: open ? 180 : 0 }}
          transition={{ duration: 0.2 }}
        >
          <ChevronDown size={16} className="text-amber-600" />
        </motion.div>
      </button>

      <AnimatePresence initial={false}>
        {open && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.22 }}
            className="overflow-hidden"
          >
            <div className="px-4 pb-4 space-y-3 text-[12px] text-amber-900 leading-relaxed border-t border-amber-200/70">
              <p className="pt-3 font-semibold">⚕ For Informational Use Only</p>
              <p>
                MediFind is an AI-assisted tool designed to provide <strong>general health
                information</strong> based on the symptoms you describe. It is <strong>not</strong> a
                substitute for professional medical advice, diagnosis, or treatment.
              </p>
              <p>
                The results generated by MediFind are based on pattern recognition and publicly
                available medical knowledge. They may be incomplete, inaccurate, or not applicable
                to your specific situation.
              </p>
              <p className="font-semibold">You should always:</p>
              <ul className="list-disc pl-4 space-y-1">
                <li>Consult a qualified healthcare professional for any medical concerns.</li>
                <li>Not delay seeking medical care based on information from this app.</li>
                <li>Disclose all symptoms and medical history to your doctor.</li>
                <li>
                  In an emergency, call <strong>911</strong> (US), <strong>112</strong> (EU), or{' '}
                  <strong>108</strong> (India) immediately.
                </li>
              </ul>
              <p>
                MediFind, its developers, and affiliated parties accept <strong>no liability</strong>{' '}
                for actions taken or not taken based on the information provided by this application.
              </p>
              <p className="text-amber-700 font-medium">
                By using MediFind you acknowledge and agree to these terms.
              </p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}
