// Symptom synonym / normalisation map for the local diagnosis engine.
// Both user input AND every disease entry's symptom names are passed through
// this same map before matching (see tokenizer.js normalize()), so it does
// not matter whether a disease was authored using "runny nose" or
// "rhinorrhea" — both sides converge on the canonical term below.
//
// Keys are matched as whole phrases (word-boundary safe, case-insensitive)
// against the normalised input text. Longer phrases are matched before
// shorter ones so "shortness of breath" wins over a bare "breath".
//
// Covers: plain colloquial English, common Indian-English phrasing, and a
// handful of frequent misspellings.
export const SYNONYM_MAP = {
  // ── Gastrointestinal ─────────────────────────────────────────────────────
  'stomach ache': 'abdominal pain',
  'stomach pain': 'abdominal pain',
  'tummy ache': 'abdominal pain',
  'tummy pain': 'abdominal pain',
  'tummy hurts': 'abdominal pain',
  'belly ache': 'abdominal pain',
  'belly pain': 'abdominal pain',
  'gastric pain': 'abdominal pain',
  'stomach cramps': 'abdominal cramps',
  'throwing up': 'vomiting',
  'threw up': 'vomiting',
  'puking': 'vomiting',
  'being sick': 'vomiting',
  'feeling sick': 'nausea',
  'loose motion': 'diarrhea',
  'loose motions': 'diarrhea',
  'loose stools': 'diarrhea',
  'watery stools': 'diarrhea',
  'frequent motions': 'diarrhea',
  'stomach upset': 'gastroenteritis',
  'upset stomach': 'gastroenteritis',
  'can\'t poop': 'constipation',
  'cannot poop': 'constipation',
  'hard stools': 'constipation',
  'not passing stool': 'constipation',
  'blood in poop': 'blood in stool',
  'blood in motion': 'blood in stool',
  'acidity': 'acid reflux',
  'heartburn': 'acid reflux',
  'gas trouble': 'bloating',
  'gassy': 'bloating',
  'bloated': 'bloating',
  'burping a lot': 'belching',
  'no appetite': 'loss of appetite',
  'not eating': 'loss of appetite',
  'don\'t feel like eating': 'loss of appetite',
  'yellow skin': 'jaundice',
  'yellow eyes': 'jaundice',
  'yellowish eyes': 'jaundice',

  // ── Respiratory ──────────────────────────────────────────────────────────
  'runny nose': 'rhinorrhea',
  'running nose': 'rhinorrhea',
  'nose is running': 'rhinorrhea',
  'blocked nose': 'nasal congestion',
  'stuffy nose': 'nasal congestion',
  'stuffed up': 'nasal congestion',
  'clogged nose': 'nasal congestion',
  'short of breath': 'dyspnea',
  'shortness of breath': 'dyspnea',
  'breathless': 'dyspnea',
  'can\'t breathe': 'dyspnea',
  'cannot breathe': 'dyspnea',
  'trouble breathing': 'dyspnea',
  'difficulty breathing': 'dyspnea',
  'hard to breathe': 'dyspnea',
  'chest tightness': 'chest pain',
  'chest feels tight': 'chest pain',
  'chest heaviness': 'chest pain',
  'wheezy': 'wheezing',
  'whistling breath': 'wheezing',
  'dry cough': 'cough',
  'wet cough': 'productive cough',
  'coughing up phlegm': 'productive cough',
  'coughing up mucus': 'productive cough',
  'coughing blood': 'hemoptysis',
  'blood in sputum': 'hemoptysis',
  'blood when coughing': 'hemoptysis',
  'sore throat': 'throat pain',
  'scratchy throat': 'throat pain',
  'throat hurts': 'throat pain',
  'hoarse voice': 'hoarseness',
  'losing my voice': 'hoarseness',
  'stopped up ears': 'ear congestion',
  'sneezing a lot': 'sneezing',

  // ── Neurological ─────────────────────────────────────────────────────────
  'head is spinning': 'vertigo',
  'room is spinning': 'vertigo',
  'spinning sensation': 'vertigo',
  'feeling dizzy': 'dizziness',
  'lightheaded': 'dizziness',
  'light headed': 'dizziness',
  'feel faint': 'dizziness',
  'about to faint': 'dizziness',
  'passed out': 'loss of consciousness',
  'blacked out': 'loss of consciousness',
  'fainted': 'loss of consciousness',
  'pins and needles': 'tingling',
  'numbness and tingling': 'numbness',
  'can\'t feel my': 'numbness',
  'cannot feel my': 'numbness',
  'seeing double': 'double vision',
  'blurry vision': 'blurred vision',
  'blurred eyesight': 'blurred vision',
  'can\'t sleep': 'insomnia',
  'cannot sleep': 'insomnia',
  'trouble sleeping': 'insomnia',
  'difficulty sleeping': 'insomnia',
  'not able to sleep': 'insomnia',
  'memory problems': 'memory loss',
  'forgetting things': 'memory loss',
  'slurred speech': 'speech difficulty',
  'can\'t speak properly': 'speech difficulty',
  'face drooping': 'facial droop',
  'one side of face': 'facial droop',
  'weak on one side': 'one-sided weakness',
  'weakness on one side': 'one-sided weakness',
  'fits': 'seizure',
  'convulsions': 'seizure',
  'shaking fit': 'seizure',

  // ── Musculoskeletal / pain ───────────────────────────────────────────────
  'body pains': 'body aches',
  'body ache': 'body aches',
  'muscle pains': 'myalgia',
  'muscle aches': 'myalgia',
  'sore muscles': 'myalgia',
  'joint pains': 'joint pain',
  'aching joints': 'joint pain',
  'stiff joints': 'joint stiffness',
  'back ache': 'back pain',
  'backache': 'back pain',
  'lower back ache': 'lower back pain',
  'neck ache': 'neck pain',
  'stiff neck': 'neck stiffness',
  'sharp pain': 'sharp pain',
  'dull ache': 'dull pain',
  'shooting pain': 'sharp pain',
  'throbbing pain': 'throbbing headache',

  // ── Urological / renal ───────────────────────────────────────────────────
  'burning pee': 'dysuria',
  'burning urination': 'dysuria',
  'burning while urinating': 'dysuria',
  'pain when peeing': 'dysuria',
  'pain while urinating': 'dysuria',
  'peeing a lot': 'frequent urination',
  'peeing frequently': 'frequent urination',
  'frequent peeing': 'frequent urination',
  'weeing a lot': 'frequent urination',
  'blood in pee': 'blood in urine',
  'blood in urine': 'hematuria',
  'cloudy urine': 'cloudy urine',
  'dark urine': 'dark urine',
  'foamy urine': 'foamy urine',
  'can\'t pee': 'urinary retention',
  'cannot urinate': 'urinary retention',
  'not able to pass urine': 'urinary retention',

  // ── Cardiovascular ───────────────────────────────────────────────────────
  'racing heart': 'palpitations',
  'heart racing': 'palpitations',
  'heart pounding': 'palpitations',
  'fluttering heart': 'palpitations',
  'skipped heartbeat': 'palpitations',
  // NOT a synonym of 'palpitations' — collapsing it here made
  // heart_arrhythmia_afib's own 'irregular heartbeat' differentiating
  // symptom auto-match on ANY palpitations phrasing (palpitations can be
  // perfectly regular, e.g. anxiety/sinus tachycardia; irregularity is the
  // specific AFib-distinguishing finding). That free extra score let a
  // single bare word ("racing heart") cross the qualifying threshold with
  // no other symptom mentioned. Kept as its own literal, unmapped token.
  'bp high': 'hypertension',
  'bp is high': 'hypertension',
  'high bp': 'hypertension',
  'high blood pressure': 'hypertension',
  'bp low': 'hypotension',
  'bp is low': 'hypotension',
  'low bp': 'hypotension',
  'low blood pressure': 'hypotension',
  'swollen legs': 'leg swelling',
  'swollen feet': 'leg swelling',
  'swollen ankles': 'leg swelling',
  'legs are swollen': 'leg swelling',
  'cold hands and feet': 'poor circulation',

  // ── Skin ─────────────────────────────────────────────────────────────────
  'itchy skin': 'itching',
  'skin itching': 'itching',
  'skin rash': 'rash',
  'red spots': 'rash',
  'red patches': 'rash',
  'skin patches': 'rash',
  'bumps on skin': 'rash',
  'raised bumps': 'hives',
  'itchy bumps': 'hives',
  'skin peeling': 'peeling skin',
  'flaky skin': 'peeling skin',
  'dry skin': 'dry skin',
  'skin turning white': 'depigmentation',
  'white patches on skin': 'depigmentation',
  'hair falling': 'hair loss',
  'hair fall': 'hair loss',
  'losing hair': 'hair loss',

  // ── General / constitutional ─────────────────────────────────────────────
  'high temperature': 'fever',
  'running a temperature': 'fever',
  'feeling hot': 'fever',
  'feeling feverish': 'fever',
  'chills and shivering': 'chills',
  'shivering': 'chills',
  'sweating a lot': 'excessive sweating',
  'night sweats': 'night sweats',
  'feeling tired': 'fatigue',
  'feeling weak': 'weakness',
  'no energy': 'fatigue',
  'exhausted': 'fatigue',
  'always tired': 'fatigue',
  'losing weight': 'weight loss',
  'weight dropping': 'weight loss',
  'gaining weight': 'weight gain',
  'putting on weight': 'weight gain',
  'sudden weight loss': 'unexplained weight loss',
  'sudden weight gain': 'unexplained weight gain',
  'swollen glands': 'lymph node swelling',
  'swollen lymph nodes': 'lymph node swelling',
  'lumps in neck': 'lymph node swelling',
  'pale skin': 'pallor',
  'looking pale': 'pallor',

  // ── Colloquial Indian-English shorthand ──────────────────────────────────
  'sugar problem': 'diabetes',
  'sugar issue': 'diabetes',
  'having sugar': 'diabetes',
  'my sugar': 'diabetes',
  'motions': 'diarrhea',
  'piles': 'hemorrhoids',
  'gastric': 'indigestion',
  'weakness in body': 'weakness',
  'giddiness': 'dizziness',
  'vomitting': 'vomiting', // common misspelling
  'diarrhoea': 'diarrhea',
  'oedema': 'edema',

  // ── Mental health ────────────────────────────────────────────────────────
  'feeling anxious': 'anxiety',
  'feeling nervous': 'anxiety',
  'panicking': 'panic attack',
  'feeling low': 'depressed mood',
  'feeling sad': 'depressed mood',
  'feeling down': 'depressed mood',
  'no interest in anything': 'loss of interest',
  'don\'t want to do anything': 'loss of interest',
  'racing thoughts': 'racing thoughts',
  'can\'t concentrate': 'poor concentration',
  'cannot concentrate': 'poor concentration',
  'trouble focusing': 'poor concentration',
  'mood swings': 'mood swings',

  // ── ENT / eyes ───────────────────────────────────────────────────────────
  'ear pain': 'earache',
  'ear ache': 'earache',
  'ear hurts': 'earache',
  'ringing in ears': 'tinnitus',
  'ringing ears': 'tinnitus',
  'ears ringing': 'tinnitus',
  'hearing loss': 'hearing loss',
  'can\'t hear well': 'hearing loss',
  'muffled hearing': 'hearing loss',
  'red eyes': 'eye redness',
  'eyes are red': 'eye redness',
  'itchy eyes': 'eye itching',
  'watery eyes': 'eye discharge',
  'eye discharge': 'eye discharge',
  'sticky eyes': 'eye discharge',
  'eye pain': 'eye pain',
  'eyes hurt': 'eye pain',
  'sensitive to light': 'photophobia',
  'light hurts my eyes': 'photophobia',
  'nose bleed': 'epistaxis',
  'nosebleed': 'epistaxis',
  'bleeding nose': 'epistaxis',

  // ── Women's health ───────────────────────────────────────────────────────
  'missed period': 'amenorrhea',
  'periods stopped': 'amenorrhea',
  'irregular periods': 'irregular menstruation',
  'heavy periods': 'menorrhagia',
  'heavy bleeding periods': 'menorrhagia',
  'painful periods': 'dysmenorrhea',
  'period cramps': 'dysmenorrhea',
  'pain during periods': 'dysmenorrhea',
  'vaginal discharge': 'vaginal discharge',
  'vaginal itching': 'vaginal itching',
  'painful sex': 'painful intercourse',
  'breast pain': 'breast pain',
  'breast lump': 'breast lump',

  // ── Risk-factor / context phrases ───────────────────────────────────────
  'went abroad': 'recent travel',
  'traveled recently': 'recent travel',
  'travelled recently': 'recent travel',
  'came back from': 'recent travel',
  'mosquito bite': 'mosquito exposure',
  'bitten by mosquito': 'mosquito exposure',
  'lots of mosquitoes': 'mosquito exposure',
  'ate outside food': 'ate raw or street food',
  'street food': 'ate raw or street food',
  'ate raw fish': 'ate raw or street food',
  'undercooked meat': 'ate raw or street food',
  'contaminated water': 'contaminated water exposure',
  'dirty water': 'contaminated water exposure',
  'flood water': 'contaminated water exposure',
  'animal bite': 'animal bite',
  'dog bite': 'animal bite',
  'bitten by dog': 'animal bite',
  'unprotected sex': 'unprotected sexual contact',
  'new sexual partner': 'unprotected sexual contact',
}

export default SYNONYM_MAP
