// Symptom synonym / normalisation map for the local diagnosis engine.
// Both user input AND every disease entry's symptom names are passed through
// this same map before matching (see tokenizer.js normalize()), so it does
// not matter whether a disease was authored using "runny nose" or
// "rhinorrhea" — both sides converge on the canonical term below.
//
// Keys are matched as whole phrases (word-boundary safe, case-insensitive)
// against the normalised input text. Longer phrases are matched before
// shorter ones so "shortness of breath" wins over a bare "breath".
//
// Covers: plain colloquial English, common Indian-English phrasing, and a
// handful of frequent misspellings.
export const SYNONYM_MAP = {
  // ── Gastrointestinal ─────────────────────────────────────────────────────
  'stomach ache': 'abdominal pain',
  'stomach pain': 'abdominal pain',
  'tummy ache': 'abdominal pain',
  'tummy pain': 'abdominal pain',
  'tummy hurts': 'abdominal pain',
  'belly ache': 'abdominal pain',
  'belly pain': 'abdominal pain',
  'gastric pain': 'abdominal pain',
  'stomach cramps': 'abdominal cramps',
  'throwing up': 'vomiting',
  'threw up': 'vomiting',
  'puking': 'vomiting',
  'being sick': 'vomiting',
  'feeling sick': 'nausea',
  'loose motion': 'diarrhea',
  'loose motions': 'diarrhea',
  'loose stools': 'diarrhea',
  'watery stools': 'diarrhea',
  'frequent motions': 'diarrhea',
  'stomach upset': 'gastroenteritis',
  'upset stomach': 'gastroenteritis',
  'can\'t poop': 'constipation',
  'cannot poop': 'constipation',
  'hard stools': 'constipation',
  'not passing stool': 'constipation',
  'blood in poop': 'blood in stool',
  'blood in motion': 'blood in stool',
  'acidity': 'acid reflux',
  'heartburn': 'acid reflux',
  'gas trouble': 'bloating',
  'gassy': 'bloating',
  'bloated': 'bloating',
  'burping a lot': 'belching',
  'no appetite': 'loss of appetite',
  'not eating': 'loss of appetite',
  'don\'t feel like eating': 'loss of appetite',
  'yellow skin': 'jaundice',
  'yellow eyes': 'jaundice',
  'yellowish eyes': 'jaundice',

  // ── Respiratory ──────────────────────────────────────────────────────────
  'runny nose': 'rhinorrhea',
  'running nose': 'rhinorrhea',
  'nose is running': 'rhinorrhea',
  'blocked nose': 'nasal congestion',
  'stuffy nose': 'nasal congestion',
  'stuffed up': 'nasal congestion',
  'clogged nose': 'nasal congestion',
  'short of breath': 'dyspnea',
  'shortness of breath': 'dyspnea',
  'breathless': 'dyspnea',
  'can\'t breathe': 'dyspnea',
  'cannot breathe': 'dyspnea',
  'trouble breathing': 'dyspnea',
  'difficulty breathing': 'dyspnea',
  'hard to breathe': 'dyspnea',
  // Chest tightness and chest pressure are deliberately NOT collapsed into
  // 'chest pain'. The cardiac entry lists all three as separate primary
  // symptoms, and collapsing them would make one phrase ("chest pain") match
  // three primaries at once — inflating both the score and the matched-primary
  // count from a single thing the user actually said.
  'chest tightness': 'chest tightness',
  'tightness in chest': 'chest tightness',
  'tight chest': 'chest tightness',
  'chest feels tight': 'chest tightness',
  'chest pressure': 'chest pressure',
  'pressure in chest': 'chest pressure',
  'chest heaviness': 'chest pressure',
  'heaviness in chest': 'chest pressure',
  'chest discomfort': 'chest discomfort',
  'discomfort in chest': 'chest discomfort',
  'wheezy': 'wheezing',
  'whistling breath': 'wheezing',
  'dry cough': 'cough',
  'wet cough': 'productive cough',
  'coughing up phlegm': 'productive cough',
  'coughing up mucus': 'productive cough',
  'coughing blood': 'hemoptysis',
  'blood in sputum': 'hemoptysis',
  'blood when coughing': 'hemoptysis',
  'sore throat': 'throat pain',
  'scratchy throat': 'throat pain',
  'throat hurts': 'throat pain',
  'hoarse voice': 'hoarseness',
  'losing my voice': 'hoarseness',
  'stopped up ears': 'ear congestion',
  'sneezing a lot': 'sneezing',

  // ── Neurological ─────────────────────────────────────────────────────────
  'head is spinning': 'vertigo',
  'room is spinning': 'vertigo',
  'spinning sensation': 'vertigo',
  'feeling dizzy': 'dizziness',
  'lightheaded': 'dizziness',
  'light headed': 'dizziness',
  'feel faint': 'dizziness',
  'about to faint': 'dizziness',
  'passed out': 'loss of consciousness',
  'blacked out': 'loss of consciousness',
  'fainted': 'loss of consciousness',
  'pins and needles': 'tingling',
  'numbness and tingling': 'numbness',
  'can\'t feel my': 'numbness',
  'cannot feel my': 'numbness',
  'seeing double': 'double vision',
  'blurry vision': 'blurred vision',
  'blurred eyesight': 'blurred vision',
  'can\'t sleep': 'insomnia',
  'cannot sleep': 'insomnia',
  'trouble sleeping': 'insomnia',
  'difficulty sleeping': 'insomnia',
  'not able to sleep': 'insomnia',
  'memory problems': 'memory loss',
  'forgetting things': 'memory loss',
  'slurred speech': 'speech difficulty',
  'can\'t speak properly': 'speech difficulty',
  'face drooping': 'facial droop',
  'one side of face': 'facial droop',
  'weak on one side': 'one-sided weakness',
  'weakness on one side': 'one-sided weakness',
  'fits': 'seizure',
  'convulsions': 'seizure',
  'shaking fit': 'seizure',

  // ── Musculoskeletal / pain ───────────────────────────────────────────────
  // Mapped DIRECTLY, never 'body pain' → 'body aches' → 'myalgia': the
  // replacement loop makes ONE pass in length-descending order, so a value it
  // writes is never re-scanned and a two-hop mapping silently half-applies.
  'body pains': 'myalgia',
  'body ache': 'myalgia',
  'body aches': 'myalgia',
  'body pain': 'myalgia',
  'bodyache': 'myalgia',
  'body is paining': 'myalgia',
  'body paining': 'myalgia',
  'whole body pain': 'myalgia',
  'whole body ache': 'myalgia',
  'whole body aches': 'myalgia',
  'all over pain': 'myalgia',
  'pain all over': 'myalgia',
  'pain all over the body': 'myalgia',
  'aching all over': 'myalgia',
  'muscle pain': 'myalgia',
  'muscle pains': 'myalgia',
  'muscle aches': 'myalgia',
  'sore muscles': 'myalgia',
  'joint pains': 'joint pain',
  'aching joints': 'joint pain',
  'stiff joints': 'joint stiffness',
  'back ache': 'back pain',
  'backache': 'back pain',
  'lower back ache': 'lower back pain',
  'neck ache': 'neck pain',
  'stiff neck': 'neck stiffness',
  'sharp pain': 'sharp pain',
  'dull ache': 'dull pain',
  'shooting pain': 'sharp pain',
  'throbbing pain': 'throbbing headache',

  // ── Urological / renal ───────────────────────────────────────────────────
  'burning pee': 'dysuria',
  'burning urination': 'dysuria',
  'burning while urinating': 'dysuria',
  'pain when peeing': 'dysuria',
  'pain while urinating': 'dysuria',
  'peeing a lot': 'frequent urination',
  'peeing frequently': 'frequent urination',
  'frequent peeing': 'frequent urination',
  'weeing a lot': 'frequent urination',
  'blood in pee': 'hematuria',
  'blood in urine': 'hematuria',
  'red urine': 'hematuria',
  'cloudy urine': 'cloudy urine',
  'dark urine': 'dark urine',
  'foamy urine': 'foamy urine',
  'can\'t pee': 'urinary retention',
  'cannot urinate': 'urinary retention',
  'not able to pass urine': 'urinary retention',

  // ── Cardiovascular ───────────────────────────────────────────────────────
  'racing heart': 'palpitations',
  'heart racing': 'palpitations',
  'heart pounding': 'palpitations',
  'fluttering heart': 'palpitations',
  'skipped heartbeat': 'palpitations',
  // NOT a synonym of 'palpitations' — collapsing it here made
  // heart_arrhythmia_afib's own 'irregular heartbeat' differentiating
  // symptom auto-match on ANY palpitations phrasing (palpitations can be
  // perfectly regular, e.g. anxiety/sinus tachycardia; irregularity is the
  // specific AFib-distinguishing finding). That free extra score let a
  // single bare word ("racing heart") cross the qualifying threshold with
  // no other symptom mentioned. Kept as its own literal, unmapped token.
  'bp high': 'hypertension',
  'bp is high': 'hypertension',
  'high bp': 'hypertension',
  'high blood pressure': 'hypertension',
  'bp low': 'hypotension',
  'bp is low': 'hypotension',
  'low bp': 'hypotension',
  'low blood pressure': 'hypotension',
  'swollen legs': 'leg swelling',
  'swollen feet': 'leg swelling',
  'swollen ankles': 'leg swelling',
  'legs are swollen': 'leg swelling',
  'cold hands and feet': 'poor circulation',

  // ── Skin ─────────────────────────────────────────────────────────────────
  'itchy skin': 'itching',
  'skin itching': 'itching',
  'skin rash': 'rash',
  'red spots': 'rash',
  'red patches': 'rash',
  'skin patches': 'rash',
  'bumps on skin': 'rash',
  'raised bumps': 'hives',
  'itchy bumps': 'hives',
  'skin peeling': 'peeling skin',
  'flaky skin': 'peeling skin',
  'dry skin': 'dry skin',
  'skin turning white': 'depigmentation',
  'white patches on skin': 'depigmentation',
  'hair falling': 'hair loss',
  'hair fall': 'hair loss',
  'losing hair': 'hair loss',

  // ── General / constitutional ─────────────────────────────────────────────
  'high temperature': 'fever',
  'running a temperature': 'fever',
  'feeling hot': 'fever',
  'feeling feverish': 'fever',
  'chills and shivering': 'chills',
  'shivering': 'chills',
  'sweating a lot': 'excessive sweating',
  'night sweats': 'night sweats',
  'feeling tired': 'fatigue',
  'feeling weak': 'weakness',
  'no energy': 'fatigue',
  'exhausted': 'fatigue',
  'always tired': 'fatigue',
  'losing weight': 'weight loss',
  'weight dropping': 'weight loss',
  'gaining weight': 'weight gain',
  'putting on weight': 'weight gain',
  'sudden weight loss': 'unexplained weight loss',
  'sudden weight gain': 'unexplained weight gain',
  'swollen glands': 'lymph node swelling',
  'swollen lymph nodes': 'lymph node swelling',
  'lumps in neck': 'lymph node swelling',
  'pale skin': 'pallor',
  'looking pale': 'pallor',

  // ── Colloquial Indian-English shorthand ──────────────────────────────────
  'sugar problem': 'diabetes',
  'sugar issue': 'diabetes',
  'having sugar': 'diabetes',
  'my sugar': 'diabetes',
  'motions': 'diarrhea',
  'piles': 'hemorrhoids',
  'gastric': 'indigestion',
  'weakness in body': 'weakness',
  'giddiness': 'dizziness',
  'vomitting': 'vomiting', // common misspelling
  'diarrhoea': 'diarrhea',
  'oedema': 'edema',

  // ── Mental health ────────────────────────────────────────────────────────
  'feeling anxious': 'anxiety',
  'anxious': 'anxiety',
  'feeling nervous': 'anxiety',
  'panicking': 'panic attack',
  'feeling low': 'depressed mood',
  'feeling sad': 'depressed mood',
  'feeling down': 'depressed mood',
  'no interest in anything': 'loss of interest',
  'don\'t want to do anything': 'loss of interest',
  'racing thoughts': 'racing thoughts',
  'can\'t concentrate': 'poor concentration',
  'cannot concentrate': 'poor concentration',
  'trouble focusing': 'poor concentration',
  'mood swings': 'mood swings',

  // ── ENT / eyes ───────────────────────────────────────────────────────────
  'ear pain': 'earache',
  'ear ache': 'earache',
  'ear hurts': 'earache',
  'ringing in ears': 'tinnitus',
  'ringing ears': 'tinnitus',
  'ears ringing': 'tinnitus',
  'hearing loss': 'hearing loss',
  'can\'t hear well': 'hearing loss',
  'muffled hearing': 'hearing loss',
  'red eyes': 'eye redness',
  'eyes are red': 'eye redness',
  'itchy eyes': 'eye itching',
  'watery eyes': 'eye discharge',
  'eye discharge': 'eye discharge',
  'sticky eyes': 'eye discharge',
  'eye pain': 'eye pain',
  'eyes hurt': 'eye pain',
  'sensitive to light': 'photophobia',
  'light hurts my eyes': 'photophobia',
  'nose bleed': 'epistaxis',
  'nosebleed': 'epistaxis',
  'bleeding nose': 'epistaxis',

  // ── Women's health ───────────────────────────────────────────────────────
  'missed period': 'amenorrhea',
  'periods stopped': 'amenorrhea',
  'irregular periods': 'irregular menstruation',
  'heavy periods': 'menorrhagia',
  'heavy bleeding periods': 'menorrhagia',
  'painful periods': 'dysmenorrhea',
  'period cramps': 'dysmenorrhea',
  'pain during periods': 'dysmenorrhea',
  'vaginal discharge': 'vaginal discharge',
  'vaginal itching': 'vaginal itching',
  'painful sex': 'painful intercourse',
  'breast pain': 'breast pain',
  'breast lump': 'breast lump',

  // ── Risk-factor / context phrases ───────────────────────────────────────
  'went abroad': 'recent travel',
  'traveled recently': 'recent travel',
  'travelled recently': 'recent travel',
  'came back from': 'recent travel',
  'mosquito bite': 'mosquito exposure',
  'bitten by mosquito': 'mosquito exposure',
  'lots of mosquitoes': 'mosquito exposure',
  'ate outside food': 'ate raw or street food',
  'street food': 'ate raw or street food',
  'ate raw fish': 'ate raw or street food',
  'undercooked meat': 'ate raw or street food',
  'contaminated water': 'contaminated water exposure',
  'dirty water': 'contaminated water exposure',
  'flood water': 'contaminated water exposure',
  'animal bite': 'animal bite',
  'dog bite': 'animal bite',
  'bitten by dog': 'animal bite',
  'unprotected sex': 'unprotected sexual contact',
  'new sexual partner': 'unprotected sexual contact',

  // ── Colloquial "X is paining" / "my X hurts" phrasing ────────────────────
  // Indian English forms the progressive on the body part ("my head is
  // paining") where other Englishes use a verb of sensation ("my head
  // hurts"). Both are extremely common in free-text symptom entry and
  // neither used to normalise to anything the disease entries were authored
  // with. Every variant maps DIRECTLY to the canonical token the knowledge
  // base already uses — not to the medically tidier term — because matching
  // happens on the normalised string, so the user's words and the disease
  // entry only ever meet if both land on the exact same token.
  'head is paining': 'headache',
  'head paining': 'headache',
  'head pain': 'headache',
  'head ache': 'headache',
  'my head hurts': 'headache',
  'head hurts': 'headache',
  'pain in head': 'headache',
  'pain in my head': 'headache',

  'stomach is paining': 'abdominal pain',
  'stomach paining': 'abdominal pain',
  'tummy is paining': 'abdominal pain',
  'belly is paining': 'abdominal pain',
  'stomach hurts': 'abdominal pain',
  'my stomach hurts': 'abdominal pain',
  'pain in stomach': 'abdominal pain',
  'pain in my stomach': 'abdominal pain',
  'pain in abdomen': 'abdominal pain',
  'abdomen pain': 'abdominal pain',

  'chest is paining': 'chest pain',
  'chest paining': 'chest pain',
  'chest ache': 'chest pain',
  'chest hurts': 'chest pain',
  'chest is hurting': 'chest pain',
  'my chest hurts': 'chest pain',
  'pain in chest': 'chest pain',
  'pain in my chest': 'chest pain',
  'heart pain': 'chest pain',
  'heart is paining': 'chest pain',
  'pain near heart': 'chest pain',

  'back is paining': 'back pain',
  'back paining': 'back pain',
  'my back hurts': 'back pain',
  'back hurts': 'back pain',
  'pain in back': 'back pain',
  'pain in my back': 'back pain',

  'throat is paining': 'throat pain',
  'throat paining': 'throat pain',
  'throat ache': 'throat pain',
  'sore throat': 'throat pain',
  'throat is sore': 'throat pain',
  'pain in throat': 'throat pain',

  'ear is paining': 'earache',
  'ear paining': 'earache',
  'ears hurting': 'earache',
  'ears are paining': 'earache',
  'pain in ear': 'earache',

  'leg is paining': 'leg pain',
  'legs paining': 'leg pain',
  'legs are paining': 'leg pain',
  'leg ache': 'leg pain',
  'legs hurt': 'leg pain',
  'pain in legs': 'leg pain',

  'joint pain': 'joint pain',
  'joints hurting': 'joint pain',
  'joints are paining': 'joint pain',
  'joint ache': 'joint pain',
  'joints ache': 'joint pain',
  // The knowledge base authors joint symptoms as 'joint pain' across 11
  // separate entries, so 'arthralgia' points AT it, not the other way round.
  'arthralgia': 'joint pain',

  // ── Respiratory ──────────────────────────────────────────────────────────
  'breathing problem': 'dyspnea',
  'breathing difficulty': 'dyspnea',
  'difficulty in breathing': 'dyspnea',
  'breathlessness': 'dyspnea',
  'unable to breathe': 'dyspnea',
  'cant breathe': 'dyspnea',
  'out of breath': 'dyspnea',
  'nasal discharge': 'rhinorrhea',
  'nose running': 'rhinorrhea',
  'nose is blocked': 'nasal congestion',
  'blocked nostrils': 'nasal congestion',
  'coughing': 'cough',
  'cough with phlegm': 'productive cough',
  'productive cough': 'productive cough',
  'whistling sound while breathing': 'wheezing',

  // ── Digestive ────────────────────────────────────────────────────────────
  'loose stool': 'diarrhea',
  'watery stool': 'diarrhea',
  'running stomach': 'diarrhea',
  'stomach running': 'diarrhea',
  'feeling like vomiting': 'nausea',
  'feel like vomiting': 'nausea',
  'feel like throwing up': 'nausea',
  'want to vomit': 'nausea',
  'feeling nauseous': 'nausea',
  'nauseous': 'nausea',
  'burning in chest after eating': 'acid reflux',
  'burning in the chest after eating': 'acid reflux',
  'indigestion': 'indigestion',
  'stomach discomfort': 'abdominal pain',
  'discomfort in stomach': 'abdominal pain',
  'abdominal discomfort': 'abdominal pain',
  'cant pass stool': 'constipation',
  'no motion': 'constipation',
  'not able to pass motion': 'constipation',
  'stomach bloating': 'bloating',
  'stomach gas': 'bloating',
  'gas problem': 'bloating',
  'full of gas': 'bloating',

  // ── General / constitutional ─────────────────────────────────────────────
  'temperature': 'fever',
  'running temperature': 'fever',
  'body temperature is high': 'fever',
  'feverish': 'fever',
  'shivering with cold': 'chills',
  'cold and shivering': 'chills',
  'feeling cold': 'chills',
  'rigors': 'chills',
  'tiredness': 'fatigue',
  'tired': 'fatigue',
  'lethargy': 'fatigue',
  'lethargic': 'fatigue',
  'feeling fatigued': 'fatigue',
  'very tired': 'fatigue',
  'body weakness': 'fatigue',
  'general weakness': 'fatigue',
  'feeling low on energy': 'fatigue',
  // Bare 'weakness' is deliberately NOT mapped to 'fatigue': it is a
  // substring of the stroke-warning token 'one-sided weakness', and this is a
  // phrase-level rewrite, so the rule would quietly turn the single most
  // important neurological red flag in the DB into 'one sided fatigue'.
  'dizzy': 'dizziness',
  'feeling giddy': 'dizziness',
  'giddy': 'dizziness',
  'head spinning': 'dizziness',
  'unsteady': 'dizziness',
  'sweating': 'excessive sweating',
  'cold sweat': 'excessive sweating',
  'cold sweats': 'excessive sweating',
  'sweating profusely': 'excessive sweating',
  'not feeling hungry': 'loss of appetite',
  'dont want to eat': 'loss of appetite',
  'do not want to eat': 'loss of appetite',
  'cant eat': 'loss of appetite',
  'reduced appetite': 'loss of appetite',
  'anorexia': 'loss of appetite',
  'weight reducing': 'weight loss',
  'lost weight': 'weight loss',

  // ── Skin ─────────────────────────────────────────────────────────────────
  'red patches on skin': 'rash',
  'itchy rash': 'rash',
  'rashes': 'rash',
  'breaking out in rash': 'rash',
  'itching': 'itching',
  'itchy': 'itching',
  'pruritus': 'itching',
  'scratching a lot': 'itching',
  'swelling': 'swelling',
  'puffiness': 'swelling',
  'puffy': 'swelling',
  'edema': 'swelling',
  'yellowing': 'jaundice',
  'yellowing of skin': 'jaundice',
  'yellowing of eyes': 'jaundice',
  'skin turning yellow': 'jaundice',

  // ── Urinary ──────────────────────────────────────────────────────────────
  'burning while passing urine': 'dysuria',
  'burning sensation while urinating': 'dysuria',
  'painful urination': 'dysuria',
  'pain during urination': 'dysuria',
  'urine burning': 'dysuria',
  'frequent urination': 'frequent urination',
  'urinating frequently': 'frequent urination',
  'urinary frequency': 'frequent urination',
  'going to toilet frequently': 'frequent urination',
  'passing urine often': 'frequent urination',

  // ── Neurological ─────────────────────────────────────────────────────────
  'memory loss': 'memory loss',
  'poor memory': 'memory loss',
  'memory impairment': 'memory loss',
  'keep forgetting': 'memory loss',
  'paresthesia': 'numbness',
  'hand is numb': 'numbness',
  'leg is numb': 'numbness',
  'hands are numb': 'numbness',
  'feels numb': 'numbness',
  'tingling sensation': 'tingling',
  'seizure': 'seizure',
  'convulsion': 'seizure',
  'shaking uncontrollably': 'seizure',
  'confused': 'confusion',
  'disoriented': 'confusion',
  'disorientation': 'confusion',
}

export default SYNONYM_MAP
